import {Vehicle} from './vehicle.model';

/**
 * Véhicules de démonstration (fallback)
 * Utilisés tant que l'API KeplerVO n'est pas connectée
 */
export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'land-rover-discovery',
    brand: 'Land Rover',
    model: 'Discovery Sport 2.0d 180ch R-Dynamic SE',
    year: 2020,
    mileage: '53.657 Km',
    transmission: 'Automatique',
    fuel: 'Diesel',
    price: '32.900 €',
    image: 'assets/img/Land rover/land-rover-1.jpg',
    images: [
      'assets/img/Land rover/land-rover-1.jpg',
      'assets/img/Land rover/land-rover-2.jpg',
      'assets/img/Land rover/land-rover-3.jpg',
      'assets/img/Land rover/land-rover-4.jpg',
      'assets/img/Land rover/land-rover-5.jpg'
    ],
    features: ['Toit panoramique', '7 Places', 'Garantie 12 Mois'],
    status: 'available',
    details: {
      finition: 'R-Dynamic SE BVA (Toit panoramique, 7 Places, garantie 12 Mois)',
      category: '4x4 / SUV / Crossover',
      firstRegistration: '07/2020',
      warranty: '12 Mois Agir garantie',
      exteriorColor: 'Blanc Yulong Métallisée',
      interiorColor: 'Ebony',
      fiscalPower: '10 CV',
      power: '180 ch (133 kW)',
      co2Emission: '145 g/km',
      doors: 5,
      reference: 'ELOT_1297132_3114470140',
      description: 'Suivi intégralement concession Land Rover. Diesel / Micro hybride. Kilométrage garantie : 53 657 km.',
      standardEquipment: [
        'Alarme ultrasonique',
        'Allumage automatique des phares et essuie-glaces automatiques',
        'Assistance au démarrage en côte (HSA)',
        'Bluetooth connectivity',
        'Caméra de recul',
        'Caméra stéréoscopique avec freinage d\'urgence',
        'Climatisation automatique 2 zones',
        'Console centrale avec accoudoir',
        'Contrôle de stabilité (DSC)',
        'Détecteur d\'obstacle AV/AR et caméra de recul',
        'Écran tactile Touch Pro 10"',
        'Finition Gloss Black',
        'Fixation ISOFIX sur le siège passager AV',
        'Frein de stationnement électrique',
        'Lumière d\'ambiance',
        'Miroirs de courtoisie éclairés',
        'Pavillon en tissu Morzine Light Oyster',
        'Phares LED avec feux de circulation diurnes (DRL)',
        'Prises AV/AR 12V et USB',
        'Radio numérique DAB',
        'Régulateur de vitesse avec limiteur',
        'Rétroviseurs extérieurs chauffants',
        'Système audio 180W',
        'Système d\'assistance au maintien de voie',
        'Système de freinage d\'urgence',
        'Système multimédia InControl Touch Pro',
        'Volant en cuir multifonction'
      ],
      optionalEquipment: [
        'Caméras panoramiques 3D (464 €)',
        'Black Pack Extérieur (777 €)',
        'Capteur de qualité de l\'air (87 €)',
        'Chargeur à induction (103 €)',
        'Climatisation Bi-Zone avec contrôle AR (340 €)',
        'Jantes 20" 5 branches doubles Gloss Sparkle Silver (1 848 €)',
        'Pédalier en métal Bright (206 €)',
        'Peinture métallisée Blanc Yulong (982 €)',
        'Phares antibrouillard AV (215 €)',
        'Phares Premium LED avec signature LED (1 132 €)',
        'Prises supplémentaires (145 €)',
        'Rétroviseurs photosensibles, chauffants, rabattables (515 €)',
        'Roue de secours de taille réduite (248 €)',
        'Seconde rangée de sièges réglable (566 €)',
        'Sièges AV chauffants réglables électriquement 12x12 (422 €)',
        'Sièges en cuir Windsor Ebony (5 102 €)',
        'Système d\'entrée sans clé (530 €)',
        'Tapis de sol (108 €)',
        'Toit panoramique fixe (1 513 €)',
        'Vitrage AR fumé (442 €)',
        'Volant chauffant (258 €)',
        'Wade Sensing'
      ]
    }
  },
  {
    id: 'fiat-500e',
    brand: 'Fiat',
    model: '500 e 118ch Icone Plus 42 kwh',
    year: 2021,
    mileage: '26.808 Km',
    transmission: 'Automatique',
    fuel: 'Électrique',
    price: '16.900 €',
    image: 'assets/img/E 118CH/fiat-500-e118.jpg',
    images: ['assets/img/E 118CH/fiat-500-e118.jpg'],
    features: ['1ère Main', 'Toit Panoramique'],
    status: 'available'
  },
  {
    id: 'renault-clio',
    brand: 'Renault',
    model: 'Clio 5 1.0 Sce 65 ch Business',
    year: 2021,
    mileage: '48.364 Km',
    transmission: 'Manuelle',
    fuel: 'Essence',
    price: '11.990 €',
    image: 'assets/img/5 1.0/194698179-normal.jpg',
    images: ['assets/img/5 1.0/194698179-normal.jpg'],
    features: ['1ère Main', 'Radar de recul', 'GPS', 'Garantie 12 Mois'],
    status: 'available'
  },
  {
    id: 'jeep-compass',
    brand: 'Jeep',
    model: 'Compass 2.0 L Multijet 140 ch 4x4',
    year: 2018,
    mileage: '104.658 Km',
    transmission: 'Manuelle',
    fuel: 'Diesel',
    price: '15.800 €',
    image: 'assets/img/2.0 L multijet/194450657-normal.jpg',
    images: ['assets/img/2.0 L multijet/194450657-normal.jpg'],
    features: ['Active Drive', '4x4', 'Longitude'],
    status: 'available'
  },
  {
    id: 'fiat-talento',
    brand: 'Fiat',
    model: 'Talento L2 H1 6 places 1.6 Multijet 120',
    year: 2018,
    mileage: '90.924 Km',
    transmission: 'Manuelle',
    fuel: 'Diesel',
    price: '19.800 €',
    image: 'assets/img/l2 H16/194136723-normal.jpg',
    images: ['assets/img/l2 H16/194136723-normal.jpg'],
    features: ['Attelage', 'Protection bois', '1ère Main', 'Pack Pro Nav'],
    status: 'available'
  },
  {
    id: 'lexus-ux',
    brand: 'Lexus',
    model: 'UX 250h 2WD F Sport',
    year: 2022,
    mileage: '24.600 Km',
    transmission: 'Automatique',
    fuel: 'Hybride',
    price: '27.800 €',
    image: 'assets/img/250H/193654908-normal.jpg',
    images: ['assets/img/250H/193654908-normal.jpg'],
    features: ['Bleu Saphir', '1ère Main', 'Toutes options'],
    status: 'available'
  }
];

